language: go
go:
  - 1.2.1

install:
  - go get -v -t ./...
  - go get -v github.com/onsi/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v code.google.com/p/go.tools/cmd/cover
  - go install -v github.com/onsi/ginkgo/ginkgo

script: PATH=$HOME/gopath/bin:$PATH ginkgo -r --randomizeAllSpecs --failOnPending --skipMeasurements --cover